name: dart_spawner
description: Runs a Dart script/File/Uri inside a new Isolate of the current Dart VM. It also can spawn a Dart File from another Dart project/package into the current Dart VM.
version: 1.1.0
homepage: https://github.com/gmpassos/dart_spawner

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.3
  yaml: ^3.1.2
  async_extension: ^1.2.4

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
  dependency_validator: ^3.2.2
  coverage: ^1.6.3
