name: dart_spawner
description: Runs a Dart script/File/Uri inside a new Isolate of the current Dart VM. It also can spawn a Dart File from another Dart project/package into the current Dart VM.
version: 1.0.3
homepage: https://github.com/gmpassos/dart_spawner

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0
  async_extension: ^1.0.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9
  dependency_validator: ^3.1.0
  test_cov: ^1.0.1
