name: dart_spawner
description: Runs a Dart script/file/project inside a new Isolate of the current process.
version: 1.0.0
homepage: https://github.com/gmpassos/dart_spawner

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0
  async_extension: ^1.0.4

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.9
  dependency_validator: ^3.1.0
  test_cov: ^1.0.1
